name: Version Increment

on:
 push:
   branches:
     - next

jobs:
 version:
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, '[RELEASE]')"
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GIT_SECRET }}
      - run: git config --global user.name 'Digitransit'
      - run: git config --global user.email 'digitransit@hsl.fi'
      - run: npm version patch -m "[RELEASE] %s"
      - run: git push
